window.$ = window.jQuery = require('jquery');
window.Isotope = require('isotope-layout');
require('popper.js');
require('bootstrap');
require('./jquery-ui');
require('./price');
require('./script');
require('./jquery.easing');
require('./counterup');
require('./owl.carousel');
window.AOS = require('./aos');
require('./main');
require('./inline-scripts');
require('./custom');
